### ISSUE TITLE
Cleanup package namespace

### ISSUE THREAD

**Issue by Gummibeer** [elbgoods/laravel-sort-positions-rule#1]
https://github.com/elbgoods/laravel-sort-positions-rule/blob/bb459ffd940d1ce91000e1644db483ec09a55b16/composer.json#L29

```diff
- "Elbgoods\\LaravelSortPositionsValidation\\": "src"
+ "Elbgoods\\SortPositionsRule\\": "src" 
```

**Comment by eisfeuer** [comment]
Namespace changed in version 1.0.1
