### ISSUE TITLE
adjust service provider name

### ISSUE THREAD

**Issue by Gummibeer** [elbgoods/laravel-sort-positions-rule#3]
https://github.com/elbgoods/laravel-sort-positions-rule/blob/bb459ffd940d1ce91000e1644db483ec09a55b16/src/LaravelSortPositionsValidationServiceProvider.php#L7

```diff
- class LaravelSortPositionsValidationServiceProvider extends ServiceProvider
+ class SortPositionsRuleServiceProvider extends ServiceProvider
```

**Comment by eisfeuer** [comment]
Namespace changed in version 1.0.1
